# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-
# stub: magentor 0.3.4 ruby lib

Gem::Specification.new do |s|
  s.name = "magentor"
  s.version = "0.3.4"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Preston Stuteville"]
  s.date = "2015-01-07"
  s.email = "preston.stuteville@gmail.com"
  s.extra_rdoc_files = [
    "README.rdoc"
  ]
  s.files = [
    "MIT-LICENSE",
    "README.rdoc",
    "Rakefile",
    "TODOS",
    "VERSION",
    "init.rb",
    "lib/magento_api/base.rb",
    "lib/magento_api/category.rb",
    "lib/magento_api/category_attribute.rb",
    "lib/magento_api/connection.rb",
    "lib/magento_api/country.rb",
    "lib/magento_api/customer.rb",
    "lib/magento_api/customer_address.rb",
    "lib/magento_api/customer_group.rb",
    "lib/magento_api/inventory.rb",
    "lib/magento_api/invoice.rb",
    "lib/magento_api/order.rb",
    "lib/magento_api/order_item.rb",
    "lib/magento_api/product.rb",
    "lib/magento_api/product_attribute.rb",
    "lib/magento_api/product_attribute_set.rb",
    "lib/magento_api/product_link.rb",
    "lib/magento_api/product_media.rb",
    "lib/magento_api/product_stock.rb",
    "lib/magento_api/product_tier_price.rb",
    "lib/magento_api/product_type.rb",
    "lib/magento_api/region.rb",
    "lib/magento_api/shipment.rb",
    "lib/magentor.rb",
    "magentor.gemspec"
  ]
  s.homepage = "http://github.com/pstuteville/magentor"
  s.rdoc_options = ["--main", "README.rdoc", "--inline-source", "--line-numbers"]
  s.require_paths = ["lib"]
  s.rubygems_version = "2.1.11"
  s.summary = "Ruby wrapper for the Magento xmlrpc api"
end

